package com.voxivoid.recipelab;

/**
 * Simplified Chinese (简体中文), first translated by Cysita (PR #50). Keys and placeholders as in
 * {@link TextEn}, plus the names English keeps as canonical data (see {@link Lang}). Every glyph used here must be in
 * the bundled font: after changing the text, run tools/subset-font.py (LangTest fails a character the font lacks).
 */
final class TextZhHans {
    private TextZhHans() {}

    static final String[][] TEXT = {
        { "lang_name", "简体中文" },
        { "lang_auto", "自动" },
        { "value_auto", "自动" },
        { "value_off", "关闭" },
        { "value_on", "开" },
        { "value_kelvin", "色温" },
        { "value_level", "等级 %1$d" },
        { "value_seconds", "%1$s 秒" },
        { "value_unknown", "未知" },
        { "state_preview", "预览" },
        { "state_active", "已启用" },
        { "mini_preview", "预览" },
        { "mini_active", "已启用" },
        { "mini_quality", "画质 → %1$s" },
        { "position_factory", "出厂" },
        { "meta_picture_effect", "照片效果 %1$s" },
        { "meta_effect_note", "（忽略创意风格，仅 JPEG）" },
        { "meta_white_balance", "白平衡 %1$s" },
        { "meta_wb_mode", "模式 %1$d" },
        { "meta_ev", "曝光补偿 %1$s" },
        { "meta_dro", "DRO %1$s" },
        { "meta_quality_change", "画质 → %1$s（当前 %2$s）" },
        { "meta_raw_effect_ignored", "RAW 已开启：照片效果不会生效" },
        { "meta_no_preview", "无实时预览：%1$s" },
        { "quality_prompt_title", "画质：%1$s → %2$s" },
        { "quality_prompt_effect", "应用此配方需要 JPEG。" },
        { "quality_prompt_style", "创意风格配方沿用出厂配方的画质。" },
        { "quality_slot_note", "尚未定位画质槽位——仅实时预览" },
        { "reset_title", "恢复出厂设置？" },
        { "reset_body", "以标准 0 / 0 / 0、自动白平衡、无效果替换当前风格并保存" },
        { "button_accept", "接受" },
        { "button_reset", "重置" },
        { "button_cancel", "取消" },
        { "locked_one", "未写入——相机将此设置设为只读：%1$s。" },
        { "locked_many", "未写入——相机将这些设置设为只读：%1$s。" },
        { "unlock_hint", "请使用 OpenMemories-Tweak（Protection → Unlock protected settings）解锁设置存储，然后重新选择配方。" },
        { "write_failed_none", "写入 %1$s（%2$s）失败：%3$s——尚未写入任何内容" },
        { "write_failed_one", "写入 %1$s（%2$s）失败：%3$s——停止前已写入 %4$d 字节" },
        { "write_failed_many", "写入 %1$s（%2$s）失败：%3$s——停止前已写入 %4$d 字节" },
        { "lock_report_none", "已检查 %1$d 个配方槽位  ·  没有只读项" },
        { "lock_report_some", "已检查 %1$d 个配方槽位  ·  %2$d 个只读：%3$s" },
        { "lock_report_unreadable", "  ·  %1$d 个无响应" },
        { "group_favourites", "收藏" },
        { "favourite_added", "%1$s 已加入收藏" },
        { "favourite_removed", "%1$s 已从收藏移除" },
        { "favourite_empty_title", "还没有收藏" },
        { "favourite_empty_hint", "在配方上长按中央键即可收藏" },
        { "picker_brand", "分类" },
        { "action_pick", "选用" },
        { "action_browse", "浏览" },
        { "action_favourite_hold", "收藏（长按）" },
        { "action_menu_hold", "菜单（长按）" },
        { "action_hide", "隐藏" },
        { "action_exit", "退出" },
        { "action_exit_hold", "退出（长按）" },
        { "action_edit", "编辑" },
        { "action_done", "完成" },
        { "action_recipes", "配方" },
        { "action_close", "关闭" },
        { "action_back", "返回" },
        { "action_move", "移动" },
        { "action_select", "选择" },
        { "action_change", "更改" },
        { "action_confirm", "确认" },
        { "action_cancel", "取消" },
        { "keys_notice", "长按 MENU 打开菜单  ·  删除键隐藏面板  ·  长按删除键重置" },
        { "status_read_failed", "读取失败：%1$s" },
        { "status_already_picked", "已经选用——无需写入" },
        { "status_picked_one", "已选用——写入 %1$d 项；重启相机后将全面生效" },
        { "status_picked_many", "已选用——写入 %1$d 项；重启相机后将全面生效" },
        { "status_not_picked", "未选用" },
        { "status_not_reset", "未重置" },
        { "status_quality_pick", "画质：%1$s——按 ENTER 选用" },
        { "status_quality_live", "画质：%1$s（定位槽位前仅实时预览）" },
        { "status_recipe_previewed", "已预览 %1$s——按 ENTER 选用" },
        { "status_snapshot_taken", "已保存 %1$d 项设置的快照。更改一项菜单设置，重新打开应用，再运行“设置差异”。" },
        { "status_diff_changed", "%1$d 项有变化  %2$s" },
        { "status_snapshot_error", "快照错误：%1$s" },
        { "status_file_failed", "写入 %1$s 失败：%2$s" },
        { "status_logger_stopped", "按键记录已停止——事件保存在 %1$s" },
        { "menu_browse", "浏览配方" },
        { "menu_browse_detail", "品牌与收藏" },
        { "menu_panel", "面板显示" },
        { "menu_panel_detail", "实时画面上保留的内容——左 / 右更改" },
        { "menu_language", "语言 / Language" },
        { "menu_language_detail", "菜单与提示——“自动”跟随相机——左 / 右更改" },
        { "menu_reset", "重置设置" },
        { "menu_reset_detail", "恢复相机的出厂风格" },
        { "menu_about", "关于" },
        { "menu_about_detail", "版本、相机、平台" },
        { "menu_dev", "开发者  >" },
        { "menu_dev_detail", "设置快照、只读检查、样片、按键记录" },
        { "panel_full", "完整" },
        { "panel_label", "标签" },
        { "panel_hidden", "隐藏" },
        { "about_title", "关于" },
        { "about_version", "版本" },
        { "about_camera", "相机" },
        { "about_platform", "平台" },
        { "about_source", "源代码" },
        { "dev_title", "开发工具" },
        { "dev_settings_snapshot", "设置快照" },
        { "dev_settings_diff", "设置差异" },
        { "dev_read_only_check", "只读检查——%1$d 个槽位" },
        { "dev_shoot_samples", "拍摄样片——%1$d 个配方" },
        { "dev_settle_delay", "稳定延时" },
        { "dev_key_logger", "按键记录" },
        { "dev_snapshot_store", "保存每个设置 ID 的当前值" },
        { "dev_snapshot_compare", "将每个设置 ID 与快照比较" },
        { "dev_locks_detail", "检查配方会写入的每个槽位是否只读" },
        { "dev_samples_detail", "按表格顺序为每个配方拍摄一张 JPEG——MENU 停止" },
        { "dev_settle_detail", "应用配方后等待一段时间再触发快门——左 / 右更改" },
        { "dev_keys_detail", "显示每个按键的扫描码——长按 MENU 退出" },
        { "dev_no_preview", "没有实时预览——样片拍摄需要相机" },
        { "dev_progress", "正在拍摄 %1$d / %2$d · %3$s——MENU 停止" },
        { "dev_done", "样片完成——已拍摄 %1$d / %2$d 张，清单位于 %3$s" },
        { "dev_stopped_none", "样片拍摄在第一张之前停止" },
        { "dev_stopped", "样片拍摄已停止——已拍摄 %1$d / %2$d 张，清单位于 %3$s" },
        { "dev_shoot_failed", "第 %1$d 张触发快门失败：%2$s——已拍摄 %3$d 张，清单位于 %4$s" },

        // ---- rows: the chip labels
        { "row_recipe", "配方" },
        { "row_style", "风格" },
        { "row_sat", "饱和度" },
        { "row_con", "对比度" },
        { "row_sharp", "锐度" },
        { "row_pp", "PP" },
        { "row_effect", "效果" },
        { "row_sub", "子选项" },
        { "row_wb", "白平衡" },
        { "row_kelvin", "色温" },
        { "row_a_b", "琥珀-蓝" },
        { "row_g_m", "绿-洋红" },
        { "row_ev", "曝光补偿" },
        { "row_dro", "DRO" },
        { "row_quality", "画质" },

        // ---- Creative Styles, by runtime name
        { "style_standard", "标准" },
        { "style_vivid", "鲜艳" },
        { "style_neutral", "中性" },
        { "style_portrait", "人像" },
        { "style_landscape", "风景" },
        { "style_mono", "黑白" },
        { "style_clear", "清澈" },
        { "style_deep", "浓郁" },
        { "style_light", "淡雅" },
        { "style_sunset", "黄昏" },
        { "style_night", "夜景" },
        { "style_red_leaves", "秋叶" },
        { "style_sepia", "棕褐色" },

        // ---- Picture Effects, by runtime key
        { "effect_off", "关闭" },
        { "effect_toy_camera", "玩具相机" },
        { "effect_pop_color", "流行色彩" },
        { "effect_posterization", "色调分离" },
        { "effect_retro_photo", "复古照片" },
        { "effect_soft_high_key", "柔和高调" },
        { "effect_part_color", "局部彩色" },
        { "effect_rough_mono", "高对比度黑白" },
        { "effect_soft_focus", "柔焦" },
        { "effect_hdr_art", "HDR 绘画" },
        { "effect_richtone_mono", "丰富色调黑白" },
        { "effect_miniature", "微缩景观" },
        { "effect_illust", "插图" },
        { "effect_watercolor", "水彩画" },

        // ---- effect sub-settings, by runtime value
        { "sub_blue", "蓝色" },
        { "sub_pink", "粉色" },
        { "sub_green", "绿色" },
        { "sub_normal", "标准" },
        { "sub_cool", "冷色" },
        { "sub_warm", "暖色" },
        { "sub_magenta", "洋红" },
        { "sub_red", "红色" },
        { "sub_yellow", "黄色" },
        { "sub_posterization_color", "彩色" },
        { "sub_posterization_bw", "黑白" },

        // ---- quality
        { "quality_raw", "RAW" },
        { "quality_raw_jpg", "RAW+JPEG" },
        { "quality_jpg_fine", "JPEG 精细" },
        { "quality_jpg_std", "JPEG 标准" },

        // ---- brands
        { "group_sony", "索尼" },
        { "group_fuji_sim", "富士模拟" },
        { "group_fuji_film", "富士胶片" },
        { "group_kodak", "柯达" },
        { "group_cine", "电影" },
        { "group_ricoh_gr", "理光 GR" },
        { "group_leica", "徕卡" },
        { "group_hasselblad", "哈苏" },
        { "group_canon_nikon", "佳能 / 尼康" },
        { "group_pana_olympus", "松下 / 奥林巴斯" },
        { "group_other_stocks", "其他胶片" },
        { "group_ilford", "伊尔福" },
        { "group_veresdenialex", "veresdenialex" },

        // ---- recipes: the display name; the canonical English stays the identifier
        { "recipe_factory_st", "出厂标准" },
        { "recipe_sony_pt_portrait", "索尼 PT（人像）" },
        { "recipe_sony_nt_neutral", "索尼 NT（中性）" },
        { "recipe_sony_vv_vivid", "索尼 VV（鲜艳）" },
        { "recipe_sony_vv2", "索尼 VV2" },
        { "recipe_sony_fl_film_like", "索尼 FL（胶片风格）" },
        { "recipe_sony_in_instant", "索尼 IN（即时）" },
        { "recipe_sony_sh_soft_high_key", "索尼 SH（柔和高调）" },
        { "recipe_provia", "PROVIA 标准" },
        { "recipe_velvia", "Velvia 鲜艳" },
        { "recipe_astia", "ASTIA 柔和" },
        { "recipe_classic_chrome", "经典正片" },
        { "recipe_classic_negative", "经典负片" },
        { "recipe_nostalgic_neg", "怀旧负片" },
        { "recipe_reala_ace", "REALA ACE" },
        { "recipe_pro_neg_std", "PRO Neg. 标准" },
        { "recipe_pro_neg_hi", "PRO Neg. 高" },
        { "recipe_eterna", "ETERNA 影院" },
        { "recipe_eterna_bleach_bypass", "ETERNA 漂白效果" },
        { "recipe_acros", "ACROS" },
        { "recipe_acros_ye_yellow_filter", "ACROS +Ye（黄色滤镜）" },
        { "recipe_acros_r_red_filter", "ACROS +R（红色滤镜）" },
        { "recipe_acros_g_green_filter", "ACROS +G（绿色滤镜）" },
        { "recipe_sepia", "棕褐色" },
        { "recipe_fuji_pro_400h", "富士 Pro 400H" },
        { "recipe_fuji_fortia_50", "富士 Fortia 50" },
        { "recipe_fuji_superia_400", "富士 Superia 400" },
        { "recipe_fuji_c200", "富士 C200" },
        { "recipe_fuji_natura_1600", "富士 Natura 1600" },
        { "recipe_kodak_portra_160", "柯达 Portra 160" },
        { "recipe_kodak_portra_400", "柯达 Portra 400" },
        { "recipe_kodak_portra_800", "柯达 Portra 800" },
        { "recipe_kodak_gold_200", "柯达 Gold 200" },
        { "recipe_kodak_ultra_max_400", "柯达 Ultra Max 400" },
        { "recipe_kodak_color_plus_200", "柯达 Color Plus 200" },
        { "recipe_kodak_ektar_100", "柯达 Ektar 100" },
        { "recipe_kodak_ektachrome_e100", "柯达 Ektachrome E100" },
        { "recipe_kodachrome_64", "Kodachrome 64" },
        { "recipe_kodak_vision3_500t_daylight", "柯达 Vision3 500T（日光）" },
        { "recipe_kodak_vision_200t_asteroid_city", "柯达 Vision 200T（小行星城）" },
        { "recipe_kodak_tri_x_400", "柯达 Tri-X 400" },
        { "recipe_kodak_t_max", "柯达 T-Max" },
        { "recipe_kodak_tri_x_1600_pushed", "柯达 Tri-X 1600（增感）" },
        { "recipe_cinestill_50d_blue_velvet", "CineStill 50D（蓝丝绒）" },
        { "recipe_cinestill_800t", "CineStill 800T" },
        { "recipe_classic_cinema", "经典电影" },
        { "recipe_rec709_video_flat_ish", "Rec.709 视频（低对比）" },
        { "recipe_gr_positive_film", "GR 正片" },
        { "recipe_gr_negative_film", "GR 负片" },
        { "recipe_gr_bleach_bypass", "GR 漂白效果" },
        { "recipe_gr_retro", "GR 复古" },
        { "recipe_gr_cross_process", "GR 正负逆冲" },
        { "recipe_gr_hi_contrast_b_w", "GR 高对比度黑白" },
        { "recipe_gr_hard_monotone", "GR 硬调黑白" },
        { "recipe_gr_soft_monotone", "GR 柔调黑白" },
        { "recipe_leica_contemporary", "徕卡 当代" },
        { "recipe_leica_classic", "徕卡 经典" },
        { "recipe_leica_eternal", "徕卡 永恒" },
        { "recipe_leica_monochrom", "徕卡 黑白" },
        { "recipe_hasselblad_hncs_natural", "哈苏 HNCS 自然" },
        { "recipe_canon_standard", "佳能 标准" },
        { "recipe_canon_portrait", "佳能 人像" },
        { "recipe_canon_faithful", "佳能 可靠设置" },
        { "recipe_nikon_flat", "尼康 平面" },
        { "recipe_nikon_vivid", "尼康 鲜艳" },
        { "recipe_pana_l_monochrome_d", "松下 L.黑白 D" },
        { "recipe_pana_l_classicneo", "松下 L.经典 Neo" },
        { "recipe_olympus_pop_art", "奥林巴斯 浓郁色调" },
        { "recipe_olympus_pale_light", "奥林巴斯 淡化及增亮" },
        { "recipe_agfa_vista_200", "爱克发 Vista 200" },
        { "recipe_agfa_ultra_100", "爱克发 Ultra 100" },
        { "recipe_polaroid_instax", "宝丽来 / instax" },
        { "recipe_ilford_hp5", "伊尔福 HP5" },
        { "recipe_ilford_fp4", "伊尔福 FP4" },
        { "recipe_ilford_delta_100", "伊尔福 Delta 100" },
        { "recipe_ilford_delta_3200", "伊尔福 Delta 3200" },
        { "recipe_ilford_pan_f_50", "伊尔福 Pan F 50" },
        { "recipe_vektro100", "Vektro100" },
        { "recipe_vektro100_night", "Vektro100 Night" },
        { "recipe_senova_light", "Senova Light" },
        { "recipe_senova_light_night", "Senova Light Night" },
        { "recipe_portra800", "Portra800" },
        { "recipe_kodak_gold", "Kodak Gold" },
        { "recipe_kodak_gold_night", "Kodak Gold Night" },
        { "recipe_fuji400", "FUJI400" },
        { "recipe_fuji400_night", "FUJI400 Night" },
        { "recipe_evpro", "EvPro+" },
        { "recipe_evpro_night", "EvPro+ Night" },
        { "recipe_ektar100", "Ektar100" },
        { "recipe_ektar100_night", "Ektar100 Night" },
        { "recipe_blue_velvet", "Blue Velvet" },
        { "recipe_blue_velvet_night", "Blue Velvet Night" },
        { "recipe_sony_eterna_lowfi", "Sony Eterna LowFi" },
        { "recipe_sony_eterna_lowfi_night", "Sony Eterna LowFi Night" },
        { "recipe_fuji_eterna_hifi", "Fuji Eterna HiFi" },
        { "recipe_fuji_eterna_hifi_night", "Fuji Eterna HiFi Night" },
        { "recipe_classic_chrome_sambear", "Classic Chrome (SamBear)" },
        { "recipe_classic_chrome_sambear_night", "Classic Chrome (SamBear) Night" },
        { "recipe_cinestill_800t_sambear", "Cinestill 800T (SamBear)" },
        { "recipe_cinestill_800t_sambear_night", "Cinestill 800T (SamBear) Night" },
        { "recipe_vektro_100", "Vektro 100" },
        { "recipe_vektro_100_night", "Vektro 100 Night" },
        { "recipe_senova_light_sambear", "Senova Light (SamBear)" },
        { "recipe_senova_light_sambear_night", "Senova Light (SamBear) Night" },
        { "recipe_fuji_400h", "Fuji 400H" },
        { "recipe_evpro_sambear", "EvPro+ (SamBear)" },
        { "recipe_ektar_100", "Ektar 100" },
        { "recipe_portra_800", "Portra 800" },
        { "recipe_kodak_gold_sambear", "Kodak Gold (SamBear)" },
        { "recipe_blue_velvet_7400k", "Blue Velvet (7400K)" },
        { "recipe_sony_eterna", "Sony Eterna" },
        { "recipe_fuji_eterna_4300k_a3_m1_5", "Fuji Eterna 4300K A3-M1.5" },
        { "recipe_classic_chrome_4400k_a7_m0_25", "Classic Chrome 4400K A7-M0.25" },
        { "recipe_kodachrome_64_v1_3600k_a7_m0_75", "Kodachrome 64 V1 3600K A7-M0.75" },
        { "recipe_kodachrome_64_v2_4300k_a7_m1", "Kodachrome 64 V2 4300K A7-M1" },
        { "recipe_leica_chrome_64_5500k_b3_g0_5", "Leica Chrome 64 5500K B3-G0.5" },
        { "recipe_kodak_ultra_max_400_3600k_a5_5_m0_5", "Kodak Ultra Max 400 3600K A5.5-M0.5" },
        { "recipe_kodak_portra_400_4100k_a7_g1_25", "Kodak Portra 400 4100K A7-G1.25" },
        { "recipe_astia_4000k_a7_m0_5", "Astia 4000K A7-M0.5" },
        { "recipe_classic_negative_3900k_a7_m2", "Classic Negative 3900K A7-M2" },
        { "recipe_fortia_50_3500k_a7_g0_25", "Fortia 50 3500K A7-G0.25" },
        { "recipe_fortia_50_night", "Fortia 50 Night" },
        { "recipe_oktar_5500k_b1_g1", "Oktar 5500K B1-G1" },
        { "recipe_zero_mute_5500k_b1_g1", "Zero Mute 5500K B1-G1" },
        { "recipe_cinechrome_3600k_a7_g1", "CineChrome 3600K A7-G1" },
        { "recipe_kodak_portra_160_3800k_a6_g0_5", "Kodak Portra 160 3800K A6-G0.5" },
        { "recipe_pro_color_3900k_a7_g1_25", "Pro Color 3900K A7-G1.25" },
        { "recipe_ektachrome_4200k_a3_5_m0_75", "EktaChrome 4200K A3.5-M0.75" },
        { "recipe_cinestill_800t_night_3500k_a7_m1_75", "Cinestill 800T Night 3500K A7-M1.75" },
        { "recipe_delta_3200_awb", "Delta 3200 AWB" },
        { "recipe_t_max_100_awb_b3_g0_25", "T-Max 100 AWB B3-G0.25" },
        { "recipe_kosmo_pan_awb", "Kosmo Pan AWB" },
        { "recipe_chroma_fade_awb", "Chroma Fade AWB" },
        { "recipe_kodak_tri_x_1600_5500k_a3_g2", "Kodak Tri-X 1600 5500K A3-G2" },
        { "recipe_kodak_tri_x_400_5500k_a3_g2", "Kodak Tri-X 400 5500K A3-G2" },
        { "recipe_midred_infra_awb", "MidRed Infra AWB" },
        { "recipe_acros_x_awb", "Acros X AWB" },
        { "recipe_acros_xy_awb", "Acros XY AWB" },
        { "recipe_acros_xr_awb", "Acros XR AWB" },
        { "recipe_acros_xg_awb", "Acros XG AWB" },
        { "recipe_dreamneg", "DreamNeg" },
        { "recipe_dreamneg_night", "DreamNeg Night" },
        { "recipe_agfa_precisa_3200k_a7_g1_5", "Agfa Precisa 3200K A7-G1.5" },
        { "recipe_velvia_pro_5000k_b1_m1_5", "Velvia Pro 5000K B1-M1.5" },
        { "recipe_redscale_ultra_9900k_b3_g2", "RedScale Ultra 9900K B3-G2" },
        { "recipe_zetra_100_4700k_a3_5_m1_25", "Zetra 100 4700K A3.5-M1.25" },
        { "recipe_rose_spectra_3500k_a7_m0_5", "Rose Spectra 3500K A7-M0.5" },
        { "recipe_provia_rx_4000k_a3_m1_75", "Provia RX 4000K A3-M1.75" },
        { "recipe_classic_cinema_awb_a2_g0_25", "Classic Cinema AWB A2-G0.25" },
        { "recipe_kodak_color_plus_200_3700k_a7_g1_5", "Kodak Color Plus 200 3700K A7-G1.5" },
        { "recipe_neo_max_6000k_b2_5_m1_5", "Neo Max 6000K B2.5-M1.5" },
        { "recipe_nostalgic_neg_4700k_a7_m1_75", "Nostalgic Neg 4700K A7-M1.75" },
        { "recipe_cinestill_x_5500k", "Cinestill X 5500K" },
        { "recipe_asteroid_city_sambear", "Asteroid City (SamBear)" },
        { "recipe_ilford_hp5_awb_a3", "Ilford HP5 AWB A3" },
    };
}
