package com.voxivoid.recipelab;

/**
 * Vietnamese (Tiếng Việt), first translated by Brian Bui (PR #70). Keys and placeholders as in {@link TextEn}, plus the
 * names English keeps as canonical data (see {@link Lang}). Brand, film and product names stay as they are. Drawn in
 * the camera's own font (see {@link UiFont}), not a bundled one.
 */
final class TextVi {
    private TextVi() {}

    static final String[][] TEXT = {
        // ---- the Language row
        { "lang_name", "Tiếng Việt" },
        { "lang_auto", "Tự động" },

        // ---- values on the chips and in the HUD
        { "value_auto", "tự động" },
        { "value_off", "tắt" },
        { "value_on", "bật" },
        { "value_kelvin", "kelvin" },
        { "value_level", "Mức %1$d" },
        { "value_seconds", "%1$s s" },
        { "value_unknown", "không rõ" },

        // ---- the panel, the pill and the line under the recipe name
        { "state_preview", "XEM TRƯỚC" },
        { "state_active", "ĐANG DÙNG" },
        { "state_edited", "ĐÃ SỬA" },
        { "tag_jpeg_only", "Chỉ JPEG" },
        { "mini_preview", "xem trước" },
        { "mini_active", "đang dùng" },
        { "mini_quality", "chất lượng → %1$s" },
        { "meta_raw_effect_ignored", "RAW đang bật: bỏ qua hiệu ứng" },
        { "meta_no_preview", "không xem trước được: %1$s" },

        // ---- the two questions
        { "quality_prompt_title", "Chất lượng: %1$s  →  %2$s" },
        { "quality_prompt_effect", "Cần định dạng JPEG để áp dụng công thức này." },
        { "quality_prompt_style", "Công thức Creative Style dùng chất lượng của công thức Gốc." },
        { "quality_slot_note", "chưa tìm thấy cài đặt chất lượng — chỉ có thể xem trước" },
        { "reset_title", "Đặt lại về cài đặt gốc?" },
        { "reset_body", "Lưu Standard 0 / 0 / 0, cân bằng trắng tự động, không hiệu ứng, thay cho cài đặt hiện tại." },
        { "button_accept", "Đồng ý" },
        { "button_reset", "Đặt lại" },
        { "button_cancel", "Hủy" },

        // ---- writing the store
        { "locked_one", "Chưa ghi — máy ảnh giữ cài đặt này ở chế độ chỉ đọc: %1$s." },
        { "locked_many", "Chưa ghi — máy ảnh giữ các cài đặt này ở chế độ chỉ đọc: %1$s." },
        { "unlock_hint", "Mở khóa kho cài đặt bằng OpenMemories-Tweak (Protection → Unlock protected settings), rồi chọn lại công thức." },
        { "write_failed_none", "GHI THẤT BẠI tại %1$s (%2$s): %3$s — chưa ghi gì" },
        { "write_failed_one", "GHI THẤT BẠI tại %1$s (%2$s): %3$s — đã ghi %4$d byte trước khi dừng" },
        { "write_failed_many", "GHI THẤT BẠI tại %1$s (%2$s): %3$s — đã ghi %4$d byte trước khi dừng" },
        { "lock_report_none", "Đã kiểm tra %1$d ô cài đặt công thức  ·  không có ô chỉ đọc" },
        { "lock_report_some", "Đã kiểm tra %1$d ô cài đặt công thức  ·  %2$d ô chỉ đọc: %3$s" },
        { "lock_report_unreadable", "  ·  %1$d ô không phản hồi" },

        // ---- favourites and the brand list
        { "group_favourites", "Yêu thích" },
        { "favourite_added", "Đã thêm %1$s vào Yêu thích" },
        { "favourite_removed", "Đã bỏ %1$s khỏi Yêu thích" },
        { "favourite_empty_title", "Chưa có mục yêu thích nào" },
        { "favourite_empty_hint", "Giữ nút giữa trên một công thức để lưu vào đây" },
        { "picker_brand", "HÃNG" },

        // ---- custom recipes (CustomRecipes): the Custom group, the questions, the name editor, the messages
        { "group_custom", "Tùy chỉnh" },
        { "custom_empty_title", "Chưa có công thức tùy chỉnh" },
        { "custom_empty_hint", "Giữ MENU → Công thức mới, hoặc đổi công thức rồi nhấn Lưu bản mới" },
        { "custom_no_card", "Không có thẻ nhớ — công thức tùy chỉnh được lưu trên thẻ, trong thư mục RECIPES" },
        { "custom_options_body", "Công thức tùy chỉnh, lưu trên thẻ nhớ với tên %1$s" },
        { "custom_delete_title", "Xóa %1$s?" },
        { "custom_delete_body", "Xóa %1$s khỏi thẻ nhớ. Hành động này không thể hoàn tác." },
        { "button_save", "Lưu" },
        { "button_apply", "Áp dụng" },
        { "button_save_new", "Lưu bản mới" },
        { "button_discard", "Hủy thay đổi" },
        { "custom_discard_title", "Hủy thay đổi của %1$s?" },
        { "custom_discard_body", "Thay đổi chưa được lưu. Chọn Hủy thay đổi để quay lại giá trị ban đầu." },
        { "button_rename", "Đổi tên" },
        { "button_delete", "Xóa" },
        { "name_title_new", "Đặt tên công thức mới" },
        { "name_title_rename", "Đổi tên %1$s" },
        { "key_space", "cách" },
        { "key_ok", "XONG" },
        { "name_empty", "Vui lòng nhập tên trước" },
        { "name_too_long", "Tối đa %1$d ký tự" },
        { "name_bad_chars", "Chỉ gồm chữ, số, dấu cách và - . ' ( ) & +" },
        { "name_taken", "%1$s đã tồn tại" },
        { "custom_bad_value", "%1$s: không cho phép %2$s" },
        { "custom_twice", "%1$s được đặt 2 lần" },
        { "custom_not_yaml", "dòng %1$d không phải định dạng YAML key: value" },
        { "custom_newer", "tạo bởi Recipe Lab bản mới hơn (định dạng %1$d)" },
        { "custom_too_large", "quá lớn để làm công thức" },
        { "custom_unreadable", "không thể đọc: %1$s" },
        { "custom_duplicate", "%1$s đã bị trùng tên với %2$s" },
        { "custom_skipped_one", "Đã bỏ qua %1$s" },
        { "custom_skipped_many", "Đã bỏ qua %1$d file — đầu tiên là %2$s" },
        { "custom_created", "Đã lưu %1$s vào thẻ nhớ dưới tên %2$s" },
        { "custom_saved", "Đã lưu %1$s" },
        { "custom_renamed", "Đã đổi tên thành %1$s" },
        { "custom_deleted", "Đã xóa %1$s" },
        { "custom_save_failed", "Không thể lưu vào thẻ nhớ: %1$s" },
        { "custom_delete_failed", "Không thể xóa %1$s: %2$s" },
        { "custom_need_card", "Không có thẻ nhớ — cắm thẻ vào để lưu công thức tùy chỉnh" },
        { "custom_capture_failed", "Không thể lưu cài đặt máy ảnh thành công thức: %1$s" },

        // ---- the legend
        { "action_pick", "chọn" },
        { "action_browse", "duyệt" },
        { "action_favourite_hold", "thích(giữ)" },
        { "action_menu_hold", "menu(giữ)" },
        { "action_hide", "ẩn" },
        { "action_exit", "thoát" },
        { "action_exit_hold", "thoát(giữ)" },
        { "action_edit", "sửa" },
        { "action_done", "xong" },
        { "action_recipes", "công thức" },
        { "action_close", "đóng" },
        { "action_back", "trở về" },
        { "action_move", "di chuyển" },
        { "action_select", "chọn" },
        { "action_change", "đổi" },
        { "action_cancel", "hủy" },
        { "action_options_hold", "tùy chọn(giữ)" },
        { "action_type", "nhập" },
        { "action_delete_char", "xóa" },
        { "keys_notice", "Giữ MENU để mở menu  ·  Nút Xóa để ẩn menu  ·  Giữ nút Xóa để đặt lại" },

        // ---- toasts
        { "status_read_failed", "Đọc thất bại: %1$s" },
        { "status_already_picked", "Đã áp dụng — không có gì để lưu" },
        { "status_picked_one", "Đã chọn — đã lưu %1$d giá trị" },
        { "status_picked_many", "Đã chọn — đã lưu %1$d giá trị" },
        { "status_not_picked", "Chưa chọn" },
        { "status_not_reset", "Chưa đặt lại" },
        { "status_quality_pick", "Chất lượng: %1$s  — ENTER để chọn" },
        { "status_quality_live", "Chất lượng: %1$s  (chỉ xem trực tiếp cho đến khi tìm thấy cài đặt)" },
        { "status_recipe_previewed", "Đang xem trước %1$s — ENTER để chọn" },
        { "status_snapshot_taken", "Đã lưu bản chụp %1$d cài đặt. Đổi một cài đặt trong menu, mở lại ứng dụng, rồi chạy So sánh cài đặt." },
        { "status_diff_changed", "%1$d thay đổi  %2$s" },
        { "status_snapshot_error", "lỗi bản chụp cài đặt: %1$s" },
        { "status_file_failed", "Ghi %1$s thất bại: %2$s" },
        { "status_logger_stopped", "Đã dừng ghi phím — sự kiện được lưu trong %1$s" },

        // ---- the app menu
        { "menu_browse", "Duyệt công thức" },
        { "menu_browse_detail", "Hãng và Yêu thích" },
        { "menu_new", "Công thức mới" },
        { "menu_new_detail", "Lưu cài đặt hiện tại thành công thức mới" },
        { "menu_panel", "Hiển thị bảng điều khiển" },
        { "menu_panel_detail", "Tùy chọn hiển thị trên màn hình" },
        { "menu_language", "Ngôn ngữ / Language" },
        { "menu_language_detail", "Menu và thông báo — Tự động theo máy ảnh" },
        { "menu_reset", "Đặt lại cài đặt" },
        { "menu_reset_detail", "Quay lại màu gốc của máy" },
        { "menu_about", "Giới thiệu" },
        { "menu_about_detail", "Phiên bản, máy ảnh, hệ thống" },
        { "menu_dev", "Nhà phát triển  >" },
        { "menu_dev_detail", "Lưu cài đặt, kiểm tra chỉ đọc, ảnh mẫu, ghi phím" },
        { "panel_full", "Đầy đủ" },
        { "panel_no_keys", "Ẩn hướng dẫn phím" },
        { "panel_label", "Chỉ nhãn" },
        { "panel_hidden", "Ẩn" },
        { "about_title", "GIỚI THIỆU" },
        { "about_version", "phiên bản" },
        { "about_camera", "máy ảnh" },
        { "about_firmware", "firmware" },
        { "about_platform", "hệ thống" },
        { "about_source", "mã nguồn" },
        { "about_love", "Bạn thích dự án này? Hãy tài trợ!" },

        // ---- the developer menu and the sample run
        { "dev_title", "CÔNG CỤ PHÁT TRIỂN" },
        { "dev_settings_snapshot", "Lưu bản chụp cài đặt" },
        { "dev_settings_diff", "So sánh cài đặt" },
        { "dev_read_only_check", "Kiểm tra chỉ đọc — %1$d ô" },
        { "dev_shoot_samples", "Chụp ảnh mẫu — %1$d công thức" },
        { "dev_settle_delay", "Thời gian chờ ổn định" },
        { "dev_key_logger", "Ghi sự kiện phím" },
        { "dev_snapshot_store", "Lưu giá trị của mọi ID cài đặt" },
        { "dev_snapshot_compare", "So sánh mọi ID cài đặt với bản chụp đã lưu" },
        { "dev_locks_detail", "Kiểm tra cờ chỉ đọc của mọi ô mà công thức ghi vào" },
        { "dev_samples_detail", "Mỗi công thức một ảnh JPEG, theo thứ tự bảng — MENU để dừng" },
        { "dev_settle_detail", "Chờ sau khi áp dụng công thức rồi mới chụp" },
        { "dev_keys_detail", "Hiện mã quét của mọi phím — giữ MENU để thoát" },
        { "dev_no_preview", "Không có xem trực tiếp — chụp ảnh mẫu cần máy ảnh" },
        { "dev_progress", "Đang chụp %1$d / %2$d  ·  %3$s   —   MENU để dừng" },
        { "dev_done", "Chụp mẫu xong — đã chụp %1$d / %2$d ảnh, danh sách trong %3$s" },
        { "dev_stopped_none", "Đã dừng chụp mẫu trước ảnh đầu tiên" },
        { "dev_stopped", "Đã dừng chụp mẫu — đã chụp %1$d / %2$d ảnh, danh sách trong %3$s" },
        { "dev_shoot_failed", "Lỗi màn trập ở ảnh %1$d: %2$s  —  đã chụp %3$d ảnh, danh sách trong %4$s" },

        // ---- rows: the chip labels
        { "row_recipe", "CÔNG THỨC" },
        { "row_style", "PHONG CÁCH" },
        { "row_sat", "BÃO HÒA" },
        { "row_con", "TƯƠNG PHẢN" },
        { "row_sharp", "ĐỘ NÉT" },
        { "row_pp", "PP" },
        { "row_effect", "HIỆU ỨNG" },
        { "row_sub", "PHỤ" },
        { "row_wb", "WB" },
        { "row_kelvin", "KELVIN" },
        { "row_a_b", "A-B" },
        { "row_g_m", "G-M" },
        { "row_ev", "EV" },
        { "row_dro", "DRO" },
        { "row_quality", "CHẤT LƯỢNG" },

        // ---- Creative Styles, by runtime name
        { "style_standard", "tiêu chuẩn" },
        { "style_vivid", "sống động" },
        { "style_neutral", "trung tính" },
        { "style_portrait", "chân dung" },
        { "style_landscape", "phong cảnh" },
        { "style_mono", "đen trắng" },
        { "style_clear", "trong trẻo" },
        { "style_deep", "đậm" },
        { "style_light", "nhạt" },
        { "style_sunset", "hoàng hôn" },
        { "style_night", "cảnh đêm" },
        { "style_red_leaves", "lá đỏ" },
        { "style_sepia", "nâu cổ điển" },

        // ---- Picture Effects, by runtime key
        { "effect_off", "tắt" },
        { "effect_toy_camera", "máy ảnh đồ chơi" },
        { "effect_pop_color", "màu rực rỡ" },
        { "effect_posterization", "tách tông màu" },
        { "effect_retro_photo", "ảnh hoài cổ" },
        { "effect_soft_high_key", "tông sáng dịu" },
        { "effect_part_color", "giữ một màu" },
        { "effect_rough_mono", "đen trắng tương phản cao" },
        { "effect_soft_focus", "nét mềm" },
        { "effect_hdr_art", "tranh HDR" },
        { "effect_richtone_mono", "đen trắng giàu sắc độ" },
        { "effect_miniature", "thu nhỏ" },
        { "effect_illust", "minh họa" },
        { "effect_watercolor", "tranh màu nước" },

        // ---- effect sub-settings, by runtime value
        { "sub_normal", "bình thường" },
        { "sub_cool", "lạnh" },
        { "sub_warm", "ấm" },
        { "sub_green", "xanh lá" },
        { "sub_magenta", "đỏ tía" },
        { "sub_posterization_color", "màu" },
        { "sub_posterization_bw", "đen trắng" },
        { "sub_blue", "xanh dương" },
        { "sub_pink", "hồng" },
        { "sub_red", "đỏ" },
        { "sub_yellow", "vàng" },

        // ---- quality
        { "quality_raw", "RAW" },
        { "quality_raw_jpg", "RAW+JPEG" },
        { "quality_jpg_fine", "JPEG chất lượng cao" },
        { "quality_jpg_std", "JPEG tiêu chuẩn" },

        // ---- brands
        { "group_sony", "Sony" },
        { "group_fuji_sim", "Fuji Sim" },
        { "group_fuji_film", "Fuji Film" },
        { "group_kodak", "Kodak" },
        { "group_cine", "Điện ảnh" },
        { "group_ricoh_gr", "Ricoh GR" },
        { "group_leica", "Leica" },
        { "group_hasselblad", "Hasselblad" },
        { "group_canon_nikon", "Canon / Nikon" },
        { "group_pana_olympus", "Pana / Olympus" },
        { "group_other_stocks", "Phim khác" },
        { "group_ilford", "Ilford" },

        // ---- recipes: the display name; the canonical English stays the identifier
        { "recipe_factory_st", "GỐC (ST)" },
        { "recipe_sony_pt_portrait", "Sony PT (chân dung)" },
        { "recipe_sony_nt_neutral", "Sony NT (trung tính)" },
        { "recipe_sony_vv_vivid", "Sony VV (sống động)" },
        { "recipe_sony_vv2", "Sony VV2" },
        { "recipe_sony_fl_film_like", "Sony FL (giống phim)" },
        { "recipe_sony_in_instant", "Sony IN (ảnh lấy liền)" },
        { "recipe_sony_sh_soft_high_key", "Sony SH (tông sáng dịu)" },
        { "recipe_provia", "Provia" },
        { "recipe_velvia", "Velvia" },
        { "recipe_astia", "Astia" },
        { "recipe_classic_chrome", "Classic Chrome" },
        { "recipe_classic_negative", "Classic Negative" },
        { "recipe_nostalgic_neg", "Nostalgic Neg" },
        { "recipe_reala_ace", "Reala Ace" },
        { "recipe_pro_neg_std", "Pro Neg Std" },
        { "recipe_pro_neg_hi", "Pro Neg Hi" },
        { "recipe_eterna", "Eterna" },
        { "recipe_eterna_bleach_bypass", "Eterna Bleach Bypass" },
        { "recipe_acros", "Acros" },
        { "recipe_acros_ye_yellow_filter", "Acros +Ye (kính lọc vàng)" },
        { "recipe_acros_r_red_filter", "Acros +R (kính lọc đỏ)" },
        { "recipe_acros_g_green_filter", "Acros +G (kính lọc xanh lá)" },
        { "recipe_sepia", "Nâu cổ điển" },
        { "recipe_fuji_pro_400h", "Fuji Pro 400H" },
        { "recipe_fuji_fortia_50", "Fuji Fortia 50" },
        { "recipe_fuji_superia_400", "Fuji Superia 400" },
        { "recipe_fuji_c200", "Fuji C200" },
        { "recipe_fuji_natura_1600", "Fuji Natura 1600" },
        { "recipe_kodak_portra_160", "Kodak Portra 160" },
        { "recipe_kodak_portra_400", "Kodak Portra 400" },
        { "recipe_kodak_portra_800", "Kodak Portra 800" },
        { "recipe_kodak_gold_200", "Kodak Gold 200" },
        { "recipe_kodak_ultra_max_400", "Kodak Ultra Max 400" },
        { "recipe_kodak_color_plus_200", "Kodak Color Plus 200" },
        { "recipe_kodak_ektar_100", "Kodak Ektar 100" },
        { "recipe_kodak_ektachrome_e100", "Kodak Ektachrome E100" },
        { "recipe_kodachrome_64", "Kodachrome 64" },
        { "recipe_kodak_vision3_500t_daylight", "Kodak Vision3 500T (ánh sáng ngày)" },
        { "recipe_kodak_vision_200t_asteroid_city", "Kodak Vision 200T (Asteroid City)" },
        { "recipe_kodak_tri_x_400", "Kodak Tri-X 400" },
        { "recipe_kodak_t_max", "Kodak T-Max" },
        { "recipe_kodak_tri_x_1600_pushed", "Kodak Tri-X 1600 (đẩy phim)" },
        { "recipe_cinestill_50d_blue_velvet", "Cinestill 50D (Blue Velvet)" },
        { "recipe_cinestill_800t", "Cinestill 800T" },
        { "recipe_classic_cinema", "Điện ảnh cổ điển" },
        { "recipe_rec709_video_flat_ish", "Rec709 Video (hơi phẳng)" },
        { "recipe_gr_positive_film", "GR Positive Film" },
        { "recipe_gr_negative_film", "GR Negative Film" },
        { "recipe_gr_bleach_bypass", "GR Bleach Bypass" },
        { "recipe_gr_retro", "GR Retro" },
        { "recipe_gr_cross_process", "GR Cross Process" },
        { "recipe_gr_hi_contrast_b_w", "GR Hi-Contrast B&W" },
        { "recipe_gr_hard_monotone", "GR Hard Monotone" },
        { "recipe_gr_soft_monotone", "GR Soft Monotone" },
        { "recipe_leica_contemporary", "Leica Contemporary" },
        { "recipe_leica_classic", "Leica Classic" },
        { "recipe_leica_eternal", "Leica Eternal" },
        { "recipe_leica_monochrom", "Leica Monochrom" },
        { "recipe_hasselblad_hncs_natural", "Hasselblad HNCS Natural" },
        { "recipe_canon_standard", "Canon Standard" },
        { "recipe_canon_portrait", "Canon Portrait" },
        { "recipe_canon_faithful", "Canon Faithful" },
        { "recipe_nikon_flat", "Nikon Flat" },
        { "recipe_nikon_vivid", "Nikon Vivid" },
        { "recipe_pana_l_monochrome_d", "Pana L.Monochrome D" },
        { "recipe_pana_l_classicneo", "Pana L.ClassicNeo" },
        { "recipe_olympus_pop_art", "Olympus Pop Art" },
        { "recipe_olympus_pale_light", "Olympus Pale & Light" },
        { "recipe_agfa_vista_200", "Agfa Vista 200" },
        { "recipe_agfa_ultra_100", "Agfa Ultra 100" },
        { "recipe_polaroid_instax", "Polaroid / Instax" },
        { "recipe_ilford_hp5", "Ilford HP5" },
        { "recipe_ilford_fp4", "Ilford FP4" },
        { "recipe_ilford_delta_100", "Ilford Delta 100" },
        { "recipe_ilford_delta_3200", "Ilford Delta 3200" },
        { "recipe_ilford_pan_f_50", "Ilford Pan F 50" },
    };
}
