package com.voxivoid.recipelab;

final class TextVi {
    private TextVi() {}

    static final String[][] TEXT = {
        // ---- the Language row
        { "lang_name", "Tiếng Việt" },
        { "lang_auto", "Tự động" },

        // ---- values on the chips and in the HUD
        { "value_auto", "tự động" },
        { "value_off", "tắt" },
        { "value_on", "bật" },
        { "value_kelvin", "kelvin" },
        { "value_level", "Mức %1$d" },
        { "value_seconds", "%1$s s" },
        { "value_unknown", "không rõ" },

        // ---- the panel, the pill and the line under the recipe name
        { "state_preview", "XEM TRƯỚC" },
        { "state_active", "ĐANG DÙNG" },
        { "state_edited", "ĐÃ SỬA" },
        { "tag_jpeg_only", "Chỉ JPEG" },
        { "mini_preview", "xem trước" },
        { "mini_active", "đang dùng" },
        { "mini_quality", "chất lượng → %1$s" },
        { "meta_raw_effect_ignored", "RAW đang bật: bỏ qua hiệu ứng" },
        { "meta_no_preview", "không xem trước được: %1$s" },

        // ---- the two questions
        { "quality_prompt_title", "Chất lượng: %1$s  →  %2$s" },
        { "quality_prompt_effect", "Cần định dạng JPEG để áp dụng công thức này." },
        { "quality_prompt_style", "Công thức Creative Style dùng chất lượng của công thức Gốc." },
        { "quality_slot_note", "chưa tìm thấy cài đặt chất lượng — chỉ có thể xem trước" },
        { "reset_title", "Đặt lại về cài đặt gốc?" },
        { "reset_body", "Lưu Standard 0 / 0 / 0, cân bằng trắng auto, không hiệu ứng, thay cho cài đặt hiện tại." },
        { "button_accept", "Đồng ý" },
        { "button_reset", "Đặt lại" },
        { "button_cancel", "Hủy" },

        // ---- favourites and the brand list
        { "group_favourites", "Yêu thích" },
        { "favourite_added", "Đã thêm %1$s vào Yêu thích" },
        { "favourite_removed", "Đã bỏ %1$s khỏi Yêu thích" },
        { "favourite_empty_title", "Chưa có mục yêu thích nào" },
        { "favourite_empty_hint", "Giữ nút giữa trên một công thức để lưu vào đây" },
        { "picker_brand", "HÃNG" },

        // ---- custom recipes
        { "group_custom", "Tùy chỉnh" },
        { "custom_empty_title", "Chưa có công thức tùy chỉnh" },
        { "custom_empty_hint", "Giữ MENU → Công thức mới, hoặc đổi công thức rồi nhấn Lưu bản mới" },
        { "custom_no_card", "Không có thẻ nhớ — công thức tùy chỉnh được lưu trên thẻ, trong thư mục RECIPES" },
        { "custom_options_body", "Công thức tùy chỉnh, lưu trên thẻ nhớ với tên %1$s" },
        { "custom_delete_title", "Xóa %1$s?" },
        { "custom_delete_body", "Xóa %1$s khỏi thẻ nhớ. Hành động này không thể hoàn tác." },
        { "button_save", "Lưu" },
        { "button_apply", "Áp dụng" },
        { "button_save_new", "Lưu bản mới" },
        { "button_discard", "Hủy thay đổi" },
        { "custom_discard_title", "Hủy thay đổi của %1$s?" },
        { "custom_discard_body", "Thay đổi chưa được lưu. Chọn Hủy thay đổi để quay lại giá trị ban đầu." },
        { "button_rename", "Đổi tên" },
        { "button_delete", "Xóa" },
        { "name_title_new", "Đặt tên công thức mới" },
        { "name_title_rename", "Đổi tên %1$s" },
        { "key_space", "cách" },
        { "key_ok", "XONG" },
        { "name_empty", "Vui lòng nhập tên trước" },
        { "name_too_long", "Tối đa %1$d ký tự" },
        { "name_bad_chars", "Chỉ gồm chữ, số, dấu cách và - . ' ( ) & +" },
        { "name_taken", "%1$s đã tồn tại" },
        { "custom_bad_value", "%1$s: không cho phép %2$s" },
        { "custom_twice", "%1$s được đặt 2 lần" },
        { "custom_not_yaml", "dòng %1$d không phải định dạng YAML key: value" },
        { "custom_newer", "tạo bởi Recipe Lab bản mới hơn (định dạng %1$d)" },
        { "custom_too_large", "quá lớn để làm công thức" },
        { "custom_unreadable", "không thể đọc: %1$s" },
        { "custom_duplicate", "%1$s đã bị trùng tên với %2$s" },
        { "custom_skipped_one", "Đã bỏ qua %1$s" },
        { "custom_skipped_many", "Đã bỏ qua %1$d file — đầu tiên là %2$s" },
        { "custom_created", "Đã lưu %1$s vào thẻ nhớ dưới tên %2$s" },
        { "custom_saved", "Đã lưu %1$s" },
        { "custom_renamed", "Đã đổi tên thành %1$s" },
        { "custom_deleted", "Đã xóa %1$s" },
        { "custom_save_failed", "Không thể lưu vào thẻ nhớ: %1$s" },
        { "custom_delete_failed", "Không thể xóa %1$s: %2$s" },
        { "custom_need_card", "Không có thẻ nhớ — cắm thẻ vào để lưu công thức tùy chỉnh" },
        { "custom_capture_failed", "Không thể lưu cài đặt máy ảnh thành công thức: %1$s" },

        // ---- the legend
        { "action_pick", "chọn" },
        { "action_browse", "duyệt" },
        { "action_favourite_hold", "thích(giữ)" },
        { "action_menu_hold", "menu(giữ)" },
        { "action_hide", "ẩn" },
        { "action_exit", "thoát" },
        { "action_exit_hold", "thoát(giữ)" },
        { "action_edit", "sửa" },
        { "action_done", "xong" },
        { "action_recipes", "c.thức" },
        { "action_close", "đóng" },
        { "action_back", "trở về" },
        { "action_move", "di chuyển" },
        { "action_select", "chọn" },
        { "action_change", "đổi" },
        { "action_cancel", "hủy" },
        { "action_options_hold", "t.chọn(giữ)" },
        { "action_type", "nhập" },
        { "action_delete_char", "xóa" },
        { "keys_notice", "Giữ MENU để mở menu  ·  Nút Xóa để ẩn menu  ·  Giữ nút Xóa để đặt lại" },

        // ---- toasts
        { "status_read_failed", "Đọc thất bại: %1$s" },
        { "status_already_picked", "Đã áp dụng — không có gì để lưu" },
        { "status_picked_one", "Đã chọn — đã lưu %1$d giá trị" },
        { "status_picked_many", "Đã chọn — đã lưu %1$d giá trị" },
        { "status_not_picked", "Chưa chọn" },
        { "status_not_reset", "Chưa đặt lại" },
        { "status_quality_pick", "Chất lượng: %1$s  — Chọn ENTER" },
        { "status_quality_live", "Chất lượng: %1$s  (chỉ xem trực tiếp)" },

        // ---- the app menu
        { "menu_browse", "Duyệt công thức" },
        { "menu_browse_detail", "Hãng và Yêu thích" },
        { "menu_new", "Công thức mới" },
        { "menu_new_detail", "Lưu cài đặt hiện tại thành công thức mới" },
        { "menu_panel", "Hiển thị bảng điều khiển" },
        { "menu_panel_detail", "Tuỳ chọn hiển thị trên màn hình" },
        { "menu_language", "Ngôn ngữ" },
        { "menu_language_detail", "Menu và thông báo — Auto theo máy ảnh" },
        { "menu_reset", "Đặt lại cài đặt" },
        { "menu_reset_detail", "Quay lại màu gốc của máy" },
        { "menu_about", "Giới thiệu" },
        { "menu_about_detail", "Phiên bản, máy ảnh, hệ thống" },
        { "menu_dev", "Nhà phát triển  >" },
        { "menu_dev_detail", "Cài đặt, logger, snapshot" },
        { "panel_full", "Đầy đủ" },
        { "panel_no_keys", "Không phím" },
        { "panel_label", "Chỉ nhãn" },
        { "panel_hidden", "Ẩn" },
        { "about_title", "GIỚI THIỆU" },
        { "about_version", "phiên bản" },
        { "about_camera", "máy ảnh" },
        { "about_firmware", "firmware" },
        { "about_platform", "hệ thống" },
        { "about_source", "mã nguồn" },
        { "about_love", "Bạn thích dự án này? Hãy tài trợ!" },
        { "row_recipe", "row_recipe" },
        { "row_style", "row_style" },
        { "row_sat", "row_sat" },
        { "row_con", "row_con" },
        { "row_sharp", "row_sharp" },
        { "row_pp", "row_pp" },
        { "row_effect", "row_effect" },
        { "row_sub", "row_sub" },
        { "row_wb", "row_wb" },
        { "row_kelvin", "row_kelvin" },
        { "row_a_b", "row_a_b" },
        { "row_g_m", "row_g_m" },
        { "row_ev", "row_ev" },
        { "row_dro", "row_dro" },
        { "row_quality", "row_quality" },
        { "style_standard", "style_standard" },
        { "style_vivid", "style_vivid" },
        { "style_neutral", "style_neutral" },
        { "style_portrait", "style_portrait" },
        { "style_landscape", "style_landscape" },
        { "style_mono", "style_mono" },
        { "style_clear", "style_clear" },
        { "style_deep", "style_deep" },
        { "style_light", "style_light" },
        { "style_sunset", "style_sunset" },
        { "style_night", "style_night" },
        { "style_red_leaves", "style_red_leaves" },
        { "style_sepia", "style_sepia" },
        { "effect_off", "effect_off" },
        { "effect_toy_camera", "effect_toy_camera" },
        { "effect_pop_color", "effect_pop_color" },
        { "effect_posterization", "effect_posterization" },
        { "effect_retro_photo", "effect_retro_photo" },
        { "effect_soft_high_key", "effect_soft_high_key" },
        { "effect_part_color", "effect_part_color" },
        { "effect_rough_mono", "effect_rough_mono" },
        { "effect_soft_focus", "effect_soft_focus" },
        { "effect_hdr_art", "effect_hdr_art" },
        { "effect_richtone_mono", "effect_richtone_mono" },
        { "effect_miniature", "effect_miniature" },
        { "effect_illust", "effect_illust" },
        { "effect_watercolor", "effect_watercolor" },
        { "sub_blue", "sub_blue" },
        { "sub_pink", "sub_pink" },
        { "sub_green", "sub_green" },
        { "sub_normal", "sub_normal" },
        { "sub_cool", "sub_cool" },
        { "sub_warm", "sub_warm" },
        { "sub_magenta", "sub_magenta" },
        { "sub_red", "sub_red" },
        { "sub_yellow", "sub_yellow" },
        { "sub_posterization_color", "sub_posterization_color" },
        { "sub_posterization_bw", "sub_posterization_bw" },
        { "quality_raw", "quality_raw" },
        { "quality_raw_jpg", "quality_raw_jpg" },
        { "quality_jpg_fine", "quality_jpg_fine" },
        { "quality_jpg_std", "quality_jpg_std" },
        { "group_sony", "group_sony" },
        { "group_fuji_sim", "group_fuji_sim" },
        { "group_fuji_film", "group_fuji_film" },
        { "group_kodak", "group_kodak" },
        { "group_cine", "group_cine" },
        { "group_ricoh_gr", "group_ricoh_gr" },
        { "group_leica", "group_leica" },
        { "group_hasselblad", "group_hasselblad" },
        { "group_canon_nikon", "group_canon_nikon" },
        { "group_pana_olympus", "group_pana_olympus" },
        { "group_other_stocks", "group_other_stocks" },
        { "group_ilford", "group_ilford" },
        { "recipe_factory_st", "recipe_factory_st" },
        { "recipe_sony_pt_portrait", "recipe_sony_pt_portrait" },
        { "recipe_sony_nt_neutral", "recipe_sony_nt_neutral" },
        { "recipe_sony_vv_vivid", "recipe_sony_vv_vivid" },
        { "recipe_sony_vv2", "recipe_sony_vv2" },
        { "recipe_sony_fl_film_like", "recipe_sony_fl_film_like" },
        { "recipe_sony_in_instant", "recipe_sony_in_instant" },
        { "recipe_sony_sh_soft_high_key", "recipe_sony_sh_soft_high_key" },
        { "recipe_provia", "recipe_provia" },
        { "recipe_velvia", "recipe_velvia" },
        { "recipe_astia", "recipe_astia" },
        { "recipe_classic_chrome", "recipe_classic_chrome" },
        { "recipe_classic_negative", "recipe_classic_negative" },
        { "recipe_nostalgic_neg", "recipe_nostalgic_neg" },
        { "recipe_reala_ace", "recipe_reala_ace" },
        { "recipe_pro_neg_std", "recipe_pro_neg_std" },
        { "recipe_pro_neg_hi", "recipe_pro_neg_hi" },
        { "recipe_eterna", "recipe_eterna" },
        { "recipe_eterna_bleach_bypass", "recipe_eterna_bleach_bypass" },
        { "recipe_acros", "recipe_acros" },
        { "recipe_acros_ye_yellow_filter", "recipe_acros_ye_yellow_filter" },
        { "recipe_acros_r_red_filter", "recipe_acros_r_red_filter" },
        { "recipe_acros_g_green_filter", "recipe_acros_g_green_filter" },
        { "recipe_sepia", "recipe_sepia" },
        { "recipe_fuji_pro_400h", "recipe_fuji_pro_400h" },
        { "recipe_fuji_fortia_50", "recipe_fuji_fortia_50" },
        { "recipe_fuji_superia_400", "recipe_fuji_superia_400" },
        { "recipe_fuji_c200", "recipe_fuji_c200" },
        { "recipe_fuji_natura_1600", "recipe_fuji_natura_1600" },
        { "recipe_kodak_portra_160", "recipe_kodak_portra_160" },
        { "recipe_kodak_portra_400", "recipe_kodak_portra_400" },
        { "recipe_kodak_portra_800", "recipe_kodak_portra_800" },
        { "recipe_kodak_gold_200", "recipe_kodak_gold_200" },
        { "recipe_kodak_ultra_max_400", "recipe_kodak_ultra_max_400" },
        { "recipe_kodak_color_plus_200", "recipe_kodak_color_plus_200" },
        { "recipe_kodak_ektar_100", "recipe_kodak_ektar_100" },
        { "recipe_kodak_ektachrome_e100", "recipe_kodak_ektachrome_e100" },
        { "recipe_kodachrome_64", "recipe_kodachrome_64" },
        { "recipe_kodak_vision3_500t_daylight", "recipe_kodak_vision3_500t_daylight" },
        { "recipe_kodak_vision_200t_asteroid_city", "recipe_kodak_vision_200t_asteroid_city" },
        { "recipe_kodak_tri_x_400", "recipe_kodak_tri_x_400" },
        { "recipe_kodak_t_max", "recipe_kodak_t_max" },
        { "recipe_kodak_tri_x_1600_pushed", "recipe_kodak_tri_x_1600_pushed" },
        { "recipe_cinestill_50d_blue_velvet", "recipe_cinestill_50d_blue_velvet" },
        { "recipe_cinestill_800t", "recipe_cinestill_800t" },
        { "recipe_classic_cinema", "recipe_classic_cinema" },
        { "recipe_rec709_video_flat_ish", "recipe_rec709_video_flat_ish" },
        { "recipe_gr_positive_film", "recipe_gr_positive_film" },
        { "recipe_gr_negative_film", "recipe_gr_negative_film" },
        { "recipe_gr_bleach_bypass", "recipe_gr_bleach_bypass" },
        { "recipe_gr_retro", "recipe_gr_retro" },
        { "recipe_gr_cross_process", "recipe_gr_cross_process" },
        { "recipe_gr_hi_contrast_b_w", "recipe_gr_hi_contrast_b_w" },
        { "recipe_gr_hard_monotone", "recipe_gr_hard_monotone" },
        { "recipe_gr_soft_monotone", "recipe_gr_soft_monotone" },
        { "recipe_leica_contemporary", "recipe_leica_contemporary" },
        { "recipe_leica_classic", "recipe_leica_classic" },
        { "recipe_leica_eternal", "recipe_leica_eternal" },
        { "recipe_leica_monochrom", "recipe_leica_monochrom" },
        { "recipe_hasselblad_hncs_natural", "recipe_hasselblad_hncs_natural" },
        { "recipe_canon_standard", "recipe_canon_standard" },
        { "recipe_canon_portrait", "recipe_canon_portrait" },
        { "recipe_canon_faithful", "recipe_canon_faithful" },
        { "recipe_nikon_flat", "recipe_nikon_flat" },
        { "recipe_nikon_vivid", "recipe_nikon_vivid" },
        { "recipe_pana_l_monochrome_d", "recipe_pana_l_monochrome_d" },
        { "recipe_pana_l_classicneo", "recipe_pana_l_classicneo" },
        { "recipe_olympus_pop_art", "recipe_olympus_pop_art" },
        { "recipe_olympus_pale_light", "recipe_olympus_pale_light" },
        { "recipe_agfa_vista_200", "recipe_agfa_vista_200" },
        { "recipe_agfa_ultra_100", "recipe_agfa_ultra_100" },
        { "recipe_polaroid_instax", "recipe_polaroid_instax" },
        { "recipe_ilford_hp5", "recipe_ilford_hp5" },
        { "recipe_ilford_fp4", "recipe_ilford_fp4" },
        { "recipe_ilford_delta_100", "recipe_ilford_delta_100" },
        { "recipe_ilford_delta_3200", "recipe_ilford_delta_3200" },
        { "recipe_ilford_pan_f_50", "recipe_ilford_pan_f_50" },
    };
}

