package com.voxivoid.recipelab;

/**
 * Traditional Chinese (繁體中文), first translated by Cysita (PR #50). Keys and placeholders as in
 * {@link TextEn}, plus the names English keeps as canonical data (see {@link Lang}). Every glyph used here must be in
 * the bundled font: after changing the text, run tools/subset-font.py (LangTest fails a character the font lacks).
 */
final class TextZhHant {
    private TextZhHant() {}

    static final String[][] TEXT = {
        { "lang_name", "繁體中文" },
        { "lang_auto", "自動" },
        { "value_auto", "自動" },
        { "value_off", "關閉" },
        { "value_on", "開" },
        { "value_kelvin", "色溫" },
        { "value_level", "等級 %1$d" },
        { "value_seconds", "%1$s 秒" },
        { "value_unknown", "未知" },
        { "state_preview", "預覽" },
        { "state_active", "已啟用" },
        { "mini_preview", "預覽" },
        { "mini_active", "已啟用" },
        { "mini_quality", "畫質 → %1$s" },
        { "position_factory", "出廠" },
        { "meta_picture_effect", "相片效果 %1$s" },
        { "meta_effect_note", "（忽略創意風格，僅 JPEG）" },
        { "meta_white_balance", "白平衡 %1$s" },
        { "meta_wb_mode", "模式 %1$d" },
        { "meta_ev", "曝光補償 %1$s" },
        { "meta_dro", "DRO %1$s" },
        { "meta_quality_change", "畫質 → %1$s（目前 %2$s）" },
        { "meta_raw_effect_ignored", "RAW 已開啟：相片效果不會生效" },
        { "meta_no_preview", "無即時預覽：%1$s" },
        { "quality_prompt_title", "畫質：%1$s → %2$s" },
        { "quality_prompt_effect", "套用此配方需要 JPEG。" },
        { "quality_prompt_style", "創意風格配方沿用出廠配方的畫質。" },
        { "quality_slot_note", "尚未定位畫質槽位——僅即時預覽" },
        { "reset_title", "恢復出廠設定？" },
        { "reset_body", "以標準 0 / 0 / 0、自動白平衡、無效果取代目前風格並儲存" },
        { "button_accept", "接受" },
        { "button_reset", "重設" },
        { "button_cancel", "取消" },
        { "locked_one", "未寫入——相機將此設定設為唯讀：%1$s。" },
        { "locked_many", "未寫入——相機將這些設定設為唯讀：%1$s。" },
        { "unlock_hint", "請使用 OpenMemories-Tweak（Protection → Unlock protected settings）解鎖設定儲存區，然後重新選擇配方。" },
        { "write_failed_none", "寫入 %1$s（%2$s）失敗：%3$s——尚未寫入任何內容" },
        { "write_failed_one", "寫入 %1$s（%2$s）失敗：%3$s——停止前已寫入 %4$d 位元組" },
        { "write_failed_many", "寫入 %1$s（%2$s）失敗：%3$s——停止前已寫入 %4$d 位元組" },
        { "lock_report_none", "已檢查 %1$d 個配方槽位  ·  沒有唯讀項目" },
        { "lock_report_some", "已檢查 %1$d 個配方槽位  ·  %2$d 個唯讀：%3$s" },
        { "lock_report_unreadable", "  ·  %1$d 個無回應" },
        { "group_favourites", "收藏" },
        { "favourite_added", "%1$s 已加入收藏" },
        { "favourite_removed", "%1$s 已從收藏移除" },
        { "favourite_empty_title", "尚無收藏" },
        { "favourite_empty_hint", "在配方上長按中央鍵即可收藏" },
        { "picker_brand", "分類" },
        { "action_pick", "選用" },
        { "action_browse", "瀏覽" },
        { "action_favourite_hold", "收藏（長按）" },
        { "action_menu_hold", "選單（長按）" },
        { "action_hide", "隱藏" },
        { "action_exit", "退出" },
        { "action_exit_hold", "退出（長按）" },
        { "action_edit", "編輯" },
        { "action_done", "完成" },
        { "action_recipes", "配方" },
        { "action_close", "關閉" },
        { "action_back", "返回" },
        { "action_move", "移動" },
        { "action_select", "選擇" },
        { "action_change", "變更" },
        { "action_confirm", "確認" },
        { "action_cancel", "取消" },
        { "keys_notice", "長按 MENU 開啟選單  ·  刪除鍵隱藏面板  ·  長按刪除鍵重設" },
        { "status_read_failed", "讀取失敗：%1$s" },
        { "status_already_picked", "已經選用——無需寫入" },
        { "status_picked_one", "已選用——寫入 %1$d 項；重新啟動相機後將全面生效" },
        { "status_picked_many", "已選用——寫入 %1$d 項；重新啟動相機後將全面生效" },
        { "status_not_picked", "未選用" },
        { "status_not_reset", "未重設" },
        { "status_quality_pick", "畫質：%1$s——按 ENTER 選用" },
        { "status_quality_live", "畫質：%1$s（定位槽位前僅即時預覽）" },
        { "status_recipe_previewed", "已預覽 %1$s——按 ENTER 選用" },
        { "status_snapshot_taken", "已儲存 %1$d 項設定的快照。變更一項選單設定，重新開啟應用程式，再執行「設定差異」。" },
        { "status_diff_changed", "%1$d 項有變化  %2$s" },
        { "status_snapshot_error", "快照錯誤：%1$s" },
        { "status_file_failed", "寫入 %1$s 失敗：%2$s" },
        { "status_logger_stopped", "按鍵記錄已停止——事件儲存在 %1$s" },
        { "menu_browse", "瀏覽配方" },
        { "menu_browse_detail", "品牌與收藏" },
        { "menu_panel", "面板顯示" },
        { "menu_panel_detail", "即時畫面上保留的內容——左 / 右變更" },
        { "menu_language", "語言 / Language" },
        { "menu_language_detail", "選單與提示——「自動」跟隨相機——左 / 右變更" },
        { "menu_reset", "重設設定" },
        { "menu_reset_detail", "恢復相機的出廠風格" },
        { "menu_about", "關於" },
        { "menu_about_detail", "版本、相機、平台" },
        { "menu_dev", "開發者  >" },
        { "menu_dev_detail", "設定快照、唯讀檢查、樣片、按鍵記錄" },
        { "panel_full", "完整" },
        { "panel_label", "標籤" },
        { "panel_hidden", "隱藏" },
        { "about_title", "關於" },
        { "about_version", "版本" },
        { "about_camera", "相機" },
        { "about_platform", "平台" },
        { "about_source", "原始碼" },
        { "dev_title", "開發工具" },
        { "dev_settings_snapshot", "設定快照" },
        { "dev_settings_diff", "設定差異" },
        { "dev_read_only_check", "唯讀檢查——%1$d 個槽位" },
        { "dev_shoot_samples", "拍攝樣片——%1$d 個配方" },
        { "dev_settle_delay", "穩定延遲" },
        { "dev_key_logger", "按鍵記錄" },
        { "dev_snapshot_store", "儲存每個設定 ID 的目前值" },
        { "dev_snapshot_compare", "將每個設定 ID 與快照比較" },
        { "dev_locks_detail", "檢查配方會寫入的每個槽位是否唯讀" },
        { "dev_samples_detail", "依表格順序為每個配方拍攝一張 JPEG——MENU 停止" },
        { "dev_settle_detail", "套用配方後等待一段時間再觸發快門——左 / 右變更" },
        { "dev_keys_detail", "顯示每個按鍵的掃描碼——長按 MENU 離開" },
        { "dev_no_preview", "沒有即時預覽——樣片拍攝需要相機" },
        { "dev_progress", "正在拍攝 %1$d / %2$d · %3$s——MENU 停止" },
        { "dev_done", "樣片完成——已拍攝 %1$d / %2$d 張，清單位於 %3$s" },
        { "dev_stopped_none", "樣片拍攝在第一張之前停止" },
        { "dev_stopped", "樣片拍攝已停止——已拍攝 %1$d / %2$d 張，清單位於 %3$s" },
        { "dev_shoot_failed", "第 %1$d 張觸發快門失敗：%2$s——已拍攝 %3$d 張，清單位於 %4$s" },

        // ---- rows: the chip labels
        { "row_recipe", "配方" },
        { "row_style", "風格" },
        { "row_sat", "飽和度" },
        { "row_con", "對比度" },
        { "row_sharp", "銳利度" },
        { "row_pp", "PP" },
        { "row_effect", "效果" },
        { "row_sub", "子選項" },
        { "row_wb", "白平衡" },
        { "row_kelvin", "色溫" },
        { "row_a_b", "琥珀-藍" },
        { "row_g_m", "綠-洋紅" },
        { "row_ev", "曝光補償" },
        { "row_dro", "DRO" },
        { "row_quality", "畫質" },

        // ---- Creative Styles, by runtime name
        { "style_standard", "標準" },
        { "style_vivid", "鮮豔" },
        { "style_neutral", "中性" },
        { "style_portrait", "人像" },
        { "style_landscape", "風景" },
        { "style_mono", "黑白" },
        { "style_clear", "清晰" },
        { "style_deep", "濃厚" },
        { "style_light", "淡雅" },
        { "style_sunset", "夕陽" },
        { "style_night", "夜景" },
        { "style_red_leaves", "秋色" },
        { "style_sepia", "棕褐色" },

        // ---- Picture Effects, by runtime key
        { "effect_off", "關閉" },
        { "effect_toy_camera", "玩具相機" },
        { "effect_pop_color", "普普風" },
        { "effect_posterization", "色調分離" },
        { "effect_retro_photo", "復古照片" },
        { "effect_soft_high_key", "柔和高調" },
        { "effect_part_color", "局部色彩" },
        { "effect_rough_mono", "高對比黑白" },
        { "effect_soft_focus", "柔焦" },
        { "effect_hdr_art", "HDR 繪畫" },
        { "effect_richtone_mono", "豐富色調黑白" },
        { "effect_miniature", "模型" },
        { "effect_illust", "插畫" },
        { "effect_watercolor", "水彩" },

        // ---- effect sub-settings, by runtime value
        { "sub_blue", "藍色" },
        { "sub_pink", "粉紅色" },
        { "sub_green", "綠色" },
        { "sub_normal", "標準" },
        { "sub_cool", "冷色" },
        { "sub_warm", "暖色" },
        { "sub_magenta", "洋紅" },
        { "sub_red", "紅色" },
        { "sub_yellow", "黃色" },
        { "sub_posterization_color", "彩色" },
        { "sub_posterization_bw", "黑白" },

        // ---- quality
        { "quality_raw", "RAW" },
        { "quality_raw_jpg", "RAW+JPEG" },
        { "quality_jpg_fine", "JPEG 精細" },
        { "quality_jpg_std", "JPEG 標準" },

        // ---- brands
        { "group_sony", "Sony" },
        { "group_fuji_sim", "富士模擬" },
        { "group_fuji_film", "富士底片" },
        { "group_kodak", "柯達" },
        { "group_cine", "電影" },
        { "group_ricoh_gr", "Ricoh GR" },
        { "group_leica", "徠卡" },
        { "group_hasselblad", "哈蘇" },
        { "group_canon_nikon", "佳能 / 尼康" },
        { "group_pana_olympus", "松下 / 奧林巴斯" },
        { "group_other_stocks", "其他底片" },
        { "group_ilford", "伊爾福" },

        // ---- recipes: the display name; the canonical English stays the identifier
        { "recipe_factory_st", "出廠標準" },
        { "recipe_sony_pt_portrait", "Sony PT（人像）" },
        { "recipe_sony_nt_neutral", "Sony NT（中性）" },
        { "recipe_sony_vv_vivid", "Sony VV（鮮豔）" },
        { "recipe_sony_vv2", "Sony VV2" },
        { "recipe_sony_fl_film_like", "Sony FL（底片風格）" },
        { "recipe_sony_in_instant", "Sony IN（即時）" },
        { "recipe_sony_sh_soft_high_key", "Sony SH（柔和高調）" },
        { "recipe_provia", "PROVIA 標準" },
        { "recipe_velvia", "Velvia 鮮豔" },
        { "recipe_astia", "ASTIA 柔和" },
        { "recipe_classic_chrome", "經典正片" },
        { "recipe_classic_negative", "經典負片" },
        { "recipe_nostalgic_neg", "懷舊負片" },
        { "recipe_reala_ace", "REALA ACE" },
        { "recipe_pro_neg_std", "PRO Neg. 標準" },
        { "recipe_pro_neg_hi", "PRO Neg. 高" },
        { "recipe_eterna", "ETERNA 電影" },
        { "recipe_eterna_bleach_bypass", "ETERNA 漂白效果" },
        { "recipe_acros", "ACROS" },
        { "recipe_acros_ye_yellow_filter", "ACROS +Ye（黃色濾鏡）" },
        { "recipe_acros_r_red_filter", "ACROS +R（紅色濾鏡）" },
        { "recipe_acros_g_green_filter", "ACROS +G（綠色濾鏡）" },
        { "recipe_sepia", "棕褐色" },
        { "recipe_fuji_pro_400h", "富士 Pro 400H" },
        { "recipe_fuji_fortia_50", "富士 Fortia 50" },
        { "recipe_fuji_superia_400", "富士 Superia 400" },
        { "recipe_fuji_c200", "富士 C200" },
        { "recipe_fuji_natura_1600", "富士 Natura 1600" },
        { "recipe_kodak_portra_160", "柯達 Portra 160" },
        { "recipe_kodak_portra_400", "柯達 Portra 400" },
        { "recipe_kodak_portra_800", "柯達 Portra 800" },
        { "recipe_kodak_gold_200", "柯達 Gold 200" },
        { "recipe_kodak_ultra_max_400", "柯達 Ultra Max 400" },
        { "recipe_kodak_color_plus_200", "柯達 Color Plus 200" },
        { "recipe_kodak_ektar_100", "柯達 Ektar 100" },
        { "recipe_kodak_ektachrome_e100", "柯達 Ektachrome E100" },
        { "recipe_kodachrome_64", "Kodachrome 64" },
        { "recipe_kodak_vision3_500t_daylight", "柯達 Vision3 500T（日光）" },
        { "recipe_kodak_vision_200t_asteroid_city", "柯達 Vision 200T（小行星城）" },
        { "recipe_kodak_tri_x_400", "柯達 Tri-X 400" },
        { "recipe_kodak_t_max", "柯達 T-Max" },
        { "recipe_kodak_tri_x_1600_pushed", "柯達 Tri-X 1600（增感）" },
        { "recipe_cinestill_50d_blue_velvet", "CineStill 50D（藍絲絨）" },
        { "recipe_cinestill_800t", "CineStill 800T" },
        { "recipe_classic_cinema", "經典電影" },
        { "recipe_rec709_video_flat_ish", "Rec.709 影片（低對比）" },
        { "recipe_gr_positive_film", "GR 正片" },
        { "recipe_gr_negative_film", "GR 負片" },
        { "recipe_gr_bleach_bypass", "GR 漂白效果" },
        { "recipe_gr_retro", "GR 復古" },
        { "recipe_gr_cross_process", "GR 正負逆沖" },
        { "recipe_gr_hi_contrast_b_w", "GR 高對比度黑白" },
        { "recipe_gr_hard_monotone", "GR 硬調黑白" },
        { "recipe_gr_soft_monotone", "GR 柔調黑白" },
        { "recipe_leica_contemporary", "徠卡 當代" },
        { "recipe_leica_classic", "徠卡 經典" },
        { "recipe_leica_eternal", "徠卡 永恆" },
        { "recipe_leica_monochrom", "徠卡 黑白" },
        { "recipe_hasselblad_hncs_natural", "哈蘇 HNCS 自然" },
        { "recipe_canon_standard", "佳能 標準" },
        { "recipe_canon_portrait", "佳能 人像" },
        { "recipe_canon_faithful", "佳能 忠實設定" },
        { "recipe_nikon_flat", "尼康 平面" },
        { "recipe_nikon_vivid", "尼康 鮮豔" },
        { "recipe_pana_l_monochrome_d", "松下 L.黑白 D" },
        { "recipe_pana_l_classicneo", "松下 L.經典 Neo" },
        { "recipe_olympus_pop_art", "奧林巴斯 濃郁色調" },
        { "recipe_olympus_pale_light", "奧林巴斯 淡化及增亮" },
        { "recipe_agfa_vista_200", "愛克發 Vista 200" },
        { "recipe_agfa_ultra_100", "愛克發 Ultra 100" },
        { "recipe_polaroid_instax", "寶麗來 / instax" },
        { "recipe_ilford_hp5", "伊爾福 HP5" },
        { "recipe_ilford_fp4", "伊爾福 FP4" },
        { "recipe_ilford_delta_100", "伊爾福 Delta 100" },
        { "recipe_ilford_delta_3200", "伊爾福 Delta 3200" },
        { "recipe_ilford_pan_f_50", "伊爾福 Pan F 50" },
    };
}
