package com.voxivoid.recipelab;

/** Simplified Chinese presentation only. Recipe IDs, camera keys and stored data stay unchanged. */
final class Zh {
    private Zh() {}
    private static final String[][] WORDS = {
        { " values written, power-cycle the camera to apply everywhere", " 项参数，关机再开机后全面生效" },
        { " value written, power-cycle the camera to apply everywhere", " 项参数，关机再开机后全面生效" },
        { " bytes written before it stopped", " 字节已写入后中止" },
        { " byte written before it stopped", " 字节已写入后中止" },
        { ". Unlock the settings store with OpenMemories-Tweak (Protection → Unlock protected settings), then pick the recipe again.", "。可用 OpenMemories-Tweak 的 Protection → Unlock protected settings 解锁，再保存配方。" },
        { " settings taken. Change a menu setting, reopen, press C1 again.", "项。退出后改一项设置，再打开工具比较。" },
        { "Creative Style recipes use the Factory recipe's quality.", "创意风格配方沿用标准配方的画质。" },
        { "One JPEG per recipe, in table order — MENU stops the run", "每个配方拍一张 JPEG，MENU 停止" },
        { "Test every slot a recipe writes for the read-only flag", "检查配方涉及的设置是否只读" },
        { "s written, power-cycle the camera to apply everywhere", "，关机再开机后全面生效" },
        { "Wait after applying a recipe before the shutter fires", "切换配方后等待，再拍照" },
        { " written, power-cycle the camera to apply everywhere", "，关机再开机后全面生效" },
        { "Hold the centre button on a recipe to keep it here", "选中配方，长按中央键收藏" },
        { "No live preview — the sample run needs the camera", "预览不可用，无法拍摄样片" },
        { "Compare every settings id against the snapshot", "对比当前设置和上次快照" },
        { "quality slot not located yet — live view only", "未定位画质设置，只影响预览" },
        { "  (live view only until the slot is known)", "（目前只影响预览）" },
        { "Sample run stopped before the first frame", "已停止，未拍摄任何照片" },
        { "Factory values staged — ENTER to pick", "标准参数已预览，按中央键保存" },
        { " (Creative Style ignored, JPEG only)", "（创意风格不生效，仅支持 JPEG）" },
        { "JPEG is needed to apply this recipe.", "此配方需要 JPEG 画质。" },
        { "Store the value of every settings id", "记录所有设置的当前值" },
        { "Kodak Vision 200T (Asteroid City)", "柯达 Vision 200T 小行星城" },
        { "Already picked — nothing to write", "当前参数已保存，无需重复写入" },
        { "Not written — the camera holds ", "未写入，相机将" },
        { "  ·  RAW is on: effect ignored", "  ·  RAW 开启，照片效果不生效" },
        { "Kodak Vision3 500T (daylight)", "柯达 Vision3 500T 日光" },
        { "Cinestill 50D (Blue Velvet)", "Cinestill 50D 蓝丝绒" },
        { "s written before it stopped", "已写入后中止" },
        { " previewed — ENTER to pick", "：正在预览，按中央键保存" },
        { " written before it stopped", "已写入后中止" },
        { " recipe slots checked  ·  ", " 项配方设置已检查：" },
        { "Acros +Ye (yellow filter)", "Acros 黄滤镜" },
        { "Kodak Tri-X 1600 (pushed)", "柯达 Tri-X 1600 迫冲" },
        { " frames shot, listed in ", " 张，清单见" },
        { "Shutter failed on frame ", "快门失败，照片序号" },
        { "Sony SH (soft high-key)", "索尼 SH 柔和高调" },
        { "Acros +G (green filter)", "Acros 绿滤镜" },
        { "Rec709 Video (flat-ish)", "Rec709 低对比视频" },
        { "Hasselblad HNCS Natural", "哈苏 HNCS 自然" },
        { "  ·  no live preview: ", "  ·  预览不可用：" },
        { " — nothing was written", "，未写入任何内容" },
        { "Acros +R (red filter)", "Acros 红滤镜" },
        { "Kodak Ektachrome E100", "柯达 Ektachrome E100" },
        { "Sample run stopped — ", "已停止：" },
        { "Eterna Bleach Bypass", "电影 Eterna 跳漂" },
        { "Kodak Color Plus 200", "柯达 Color Plus 200" },
        { "Olympus Pale & Light", "奥林巴斯 淡雅明亮" },
        { "Sony FL (film-like)", "索尼 FL 胶片" },
        { "Kodak Ultra Max 400", "柯达 Ultra Max 400" },
        { "Pana L.Monochrome D", "松下 L.Monochrome D 黑白" },
        { "Sony PT (portrait)", "索尼 PT 人像" },
        { "GR Hi-Contrast B&W", "理光 GR 高对比黑白" },
        { "Leica Contemporary", "徕卡 现代" },
        { "Read-only check — ", "检查只读设置：" },
        { "Sony NT (neutral)", "索尼 NT 中性" },
        { "Sony IN (instant)", "索尼 IN 拍立得" },
        { "Pana L.ClassicNeo", "松下 L.ClassicNeo 经典" },
        { "Polaroid / Instax", "宝丽来／富士拍立得" },
        { "Ilford Delta 3200", "伊尔福 Delta 3200" },
        { "No favourites yet", "还没有收藏" },
        { "  — ENTER to pick", "，按中央键保存" },
        { "Settings snapshot", "记录设置快照" },
        { "   —   MENU stops", "，MENU 停止" },
        { " would not answer", " 项未响应" },
        { "Classic Negative", "经典负片 Classic Negative" },
        { "Fuji Superia 400", "富士 Superia 400" },
        { "Fuji Natura 1600", "富士 Natura 1600" },
        { "Kodak Portra 160", "柯达 Portra 160" },
        { "Kodak Portra 400", "柯达 Portra 400" },
        { "Kodak Portra 800", "柯达 Portra 800" },
        { "GR Positive Film", "理光 GR 正片" },
        { "GR Negative Film", "理光 GR 负片" },
        { "GR Bleach Bypass", "理光 GR 跳漂" },
        { "GR Cross Process", "理光 GR 交叉冲洗" },
        { "GR Hard Monotone", "理光 GR 硬调黑白" },
        { "GR Soft Monotone", "理光 GR 柔调黑白" },
        { "Ilford Delta 100", "伊尔福 Delta 100" },
        { "snapshot error: ", "快照失败：" },
        { "Shoot samples — ", "拍摄样片：" },
        { "WRITE FAILED on ", "写入失败：" },
        { "Sony VV (vivid)", "索尼 VV 鲜艳" },
        { "Kodak Ektar 100", "柯达 Ektar 100" },
        { "Kodak Tri-X 400", "柯达 Tri-X 400" },
        { "Leica Monochrom", "徕卡 黑白" },
        { "Olympus Pop Art", "奥林巴斯 波普艺术" },
        { "Ilford Pan F 50", "伊尔福 Pan F 50" },
        { "Picture Effect ", "照片效果：" },
        { "   · quality → ", "   · 画质改为" },
        { "Settle delay — ", "预览等待：" },
        { "Samples done — ", "样片完成：" },
        { "Classic Chrome", "经典正片 Classic Chrome" },
        { "Fuji Fortia 50", "富士 Fortia 50" },
        { "Kodak Gold 200", "柯达 Gold 200" },
        { "Cinestill 800T", "Cinestill 800T 钨丝灯" },
        { "Classic Cinema", "经典电影" },
        { "Canon Standard", "佳能 标准" },
        { "Canon Portrait", "佳能 人像" },
        { "Canon Faithful", "佳能 忠实" },
        { "Agfa Vista 200", "爱克发 Vista 200" },
        { "Agfa Ultra 100", "爱克发 Ultra 100" },
        { "Pana / Olympus", "松下／奥巴" },
        { " removed from ", " 已移出" },
        { "these settings", "以下设置" },
        { "none read-only", "没有只读设置" },
        { "PANA / OLYMPUS", "松下／奥巴" },
        { "Nostalgic Neg", "怀旧负片 Nostalgic Neg" },
        { "Fuji Pro 400H", "富士 Pro 400H" },
        { "Kodachrome 64", "柯达 Kodachrome 64" },
        { "Leica Classic", "徕卡 经典" },
        { "Leica Eternal", "徕卡 永恒" },
        { "Canon / Nikon", "佳能／尼康" },
        { "Read failed: ", "读取失败：" },
        { "Settings diff", "比较设置变化" },
        { "CANON / NIKON", "佳能／尼康" },
        { "FACTORY (ST)", "标准出厂 ST" },
        { "Other Stocks", "其他胶卷" },
        { "Snapshot of ", "已记录快照，共" },
        { "   · preview", "   · 预览中" },
        { "this setting", "以下设置" },
        { " read-only: ", "设为只读：" },
        { "OTHER STOCKS", "其他胶卷" },
        { "Pro Neg Std", "专业负片 标准" },
        { "Kodak T-Max", "柯达 T-Max" },
        { "Nikon Vivid", "尼康 鲜艳" },
        { "   · active", "   · 已保存" },
        { "Pro Neg Hi", "专业负片 高对比" },
        { "Nikon Flat", "尼康 平淡" },
        { "Ilford HP5", "伊尔福 HP5" },
        { "Ilford FP4", "伊尔福 FP4" },
        { "Hasselblad", "哈苏" },
        { "PP3 matrix", "PP3 色彩矩阵" },
        { "Favourites", "收藏" },
        { "FAVOURITES", "收藏" },
        { " added to ", " 已加入" },
        { "fav (hold)", "长按收藏" },
        { "Not picked", "未保存" },
        { " changed  ", " 项变化：" },
        { "HASSELBLAD", "哈苏" },
        { "Reala Ace", "富士 Reala Ace" },
        { "Fuji C200", "富士 C200" },
        { "Fuji Film", "富士胶卷" },
        { "Landscape", "风景" },
        { "Rich mono", "丰富色调黑白" },
        { "Miniature", "微缩景观" },
        { "Picked — ", "已保存：" },
        { "Quality: ", "画质：" },
        { " failed: ", "失败：" },
        { "DEV TOOLS", "开发工具" },
        { "Shooting ", "正在拍摄" },
        { "FUJI FILM", "富士胶卷" },
        { "Sony VV2", "索尼 VV2 浓艳" },
        { "GR Retro", "理光 GR 复古" },
        { "Fuji Sim", "富士模拟" },
        { "Ricoh GR", "理光 GR" },
        { "Standard", "标准" },
        { "Portrait", "人像" },
        { "High-key", "柔和高调" },
        { "Part col", "局部色彩" },
        { "Soft foc", "柔焦" },
        { "Watercol", "水彩" },
        { "JPG Fine", "JPEG 精细" },
        { " recipes", " 个配方" },
        { "FUJI SIM", "富士模拟" },
        { "RICOH GR", "理光 GR" },
        { "Neutral", "中性" },
        { "HC mono", "高对比黑白" },
        { "HDR art", "HDR 艺术" },
        { "magenta", "品红" },
        { "JPG Std", "JPEG 标准" },
        { "QUALITY", "画质" },
        { "PREVIEW", "预览中" },
        { "factory", "标准" },
        { "recipes", "配方" },
        { "confirm", "确认" },
        { "Provia", "富士 Provia 标准" },
        { "Velvia", "富士 Velvia 鲜艳" },
        { "Eterna", "电影 Eterna" },
        { "Ilford", "伊尔福" },
        { "Sunset", "日落" },
        { "Autumn", "秋叶" },
        { "Poster", "色调分离" },
        { "Illust", "插画" },
        { "normal", "标准" },
        { "yellow", "黄色" },
        { "kelvin", "色温" },
        { "RECIPE", "配方" },
        { "MATRIX", "色彩矩阵" },
        { "EFFECT", "照片效果" },
        { "KELVIN", "色温" },
        { "ACTIVE", "已保存" },
        { "browse", "浏览" },
        { "select", "选择" },
        { "cancel", "取消" },
        { "Accept", "确认" },
        { "Cancel", "取消" },
        { " value", " 项参数" },
        { " (now ", "（当前为" },
        { " slots", " 项" },
        { "ILFORD", "伊尔福" },
        { "Astia", "富士 Astia 柔和" },
        { "Acros", "Acros 黑白" },
        { "Sepia", "棕褐色" },
        { "Kodak", "柯达" },
        { "Leica", "徕卡" },
        { "Vivid", "鲜艳" },
        { "Clear", "清晰" },
        { "Light", "明亮" },
        { "Night", "夜景" },
        { "Retro", "复古照片" },
        { "green", "绿色" },
        { "color", "彩色" },
        { "STYLE", "风格" },
        { "SHARP", "锐度" },
        { "BRAND", "品牌" },
        { "close", "返回" },
        { "mode ", "模式" },
        { "  —  ", "，已拍" },
        { " byte", " 字节" },
        { "  ·  ", "  ·  " },
        { "KODAK", "柯达" },
        { "LEICA", "徕卡" },
        { "Sony", "索尼" },
        { "Cine", "电影" },
        { "Deep", "深邃" },
        { "blue", "蓝色" },
        { "pink", "粉色" },
        { "cool", "冷色" },
        { "warm", "暖色" },
        { "auto", "自动" },
        { "pick", "保存" },
        { "hide", "隐藏" },
        { "exit", "退出" },
        { "edit", "编辑" },
        { "done", "完成" },
        { "move", "移动" },
        { " of ", "／" },
        { "SONY", "索尼" },
        { "CINE", "电影" },
        { "B&W", "黑白" },
        { "Toy", "玩具相机" },
        { "Pop", "流行色彩" },
        { "red", "红色" },
        { "off", "关闭" },
        { "SAT", "饱和度" },
        { "CON", "对比度" },
        { "SUB", "效果细项" },
        { "A-B", "琥珀-蓝" },
        { "G-M", "绿-品红" },
        { "DRO", "动态范围" },
        { "MTX", "矩阵" },
        { " — ", "，" },
        { "bw", "黑白" },
        { "WB", "白平衡" },
        { "EV", "曝光补偿" },
        { "PE", "效果" },
        { "CS", "风格" },
    };
    static String text(String source) {
        if (source == null) return "";
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < source.length();) {
            boolean found = false;
            for (String[] pair : WORDS) {
                if (!source.startsWith(pair[0], i)) continue;
                int end = i + pair[0].length();
                // Do not translate a short label inside an API name, film name or exception.
                if (letter(pair[0].charAt(0)) && i > 0 && letter(source.charAt(i - 1))) continue;
                if (letter(pair[0].charAt(pair[0].length()-1)) && end < source.length() && letter(source.charAt(end))) continue;
                out.append(pair[1]); i = end; found = true; break;
            }
            if (!found) out.append(source.charAt(i++));
        }
        return out.toString();
    }
    private static boolean letter(char c) { return c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '0' && c <= '9' || c == '_' || c == '-' || c == '.'; }
}
